"""initial schema: 7 tables

Revision ID: 07295e3a126e
Revises: 
Create Date: 2026-03-21 15:35:15.872895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07295e3a126e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pair', sa.String(length=6), nullable=False),
    sa.Column('timeframe', sa.Enum('M5', 'M15', 'H1', 'H4', name='timeframe_type'), nullable=False),
    sa.Column('timestamp_ms', sa.BigInteger(), nullable=False, comment='Bar open time, Unix ms UTC'),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candles_pair_tf_ts', 'candles', ['pair', 'timeframe', 'timestamp_ms'], unique=True)
    op.create_table('feature_vectors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pair', sa.String(length=6), nullable=False),
    sa.Column('timestamp_ms', sa.BigInteger(), nullable=False, comment='Unix ms UTC'),
    sa.Column('atr_14', sa.Float(), nullable=False),
    sa.Column('adx_14', sa.Float(), nullable=False),
    sa.Column('ema_200', sa.Float(), nullable=False),
    sa.Column('bb_upper', sa.Float(), nullable=False),
    sa.Column('bb_lower', sa.Float(), nullable=False),
    sa.Column('bb_mid', sa.Float(), nullable=False),
    sa.Column('session', sa.Enum('LONDON', 'NY', 'ASIA', 'OVERLAP', name='trading_session'), nullable=False),
    sa.Column('spread_ok', sa.Boolean(), nullable=False),
    sa.Column('news_blackout', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feature_vectors_pair_ts', 'feature_vectors', ['pair', 'timestamp_ms'], unique=False)
    op.create_table('fills',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False, comment='MT5 order ticket'),
    sa.Column('pair', sa.String(length=6), nullable=False),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', name='direction_type'), nullable=False),
    sa.Column('strategy', sa.Enum('MOMENTUM', 'MEAN_REVERSION', name='strategy_type'), nullable=False),
    sa.Column('regime', sa.Enum('TRENDING_UP', 'TRENDING_DOWN', 'RANGING', 'UNDEFINED', name='regime_type'), nullable=False),
    sa.Column('requested_size', sa.Float(), nullable=False),
    sa.Column('actual_size', sa.Float(), nullable=False),
    sa.Column('requested_price', sa.Float(), nullable=False),
    sa.Column('actual_fill_price', sa.Float(), nullable=False),
    sa.Column('slippage_points', sa.Float(), nullable=False, comment='|actual - requested| / point_size'),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=False, comment='Time of fill confirmation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fills_order_id', 'fills', ['order_id'], unique=True)
    op.create_index('ix_fills_pair_filled', 'fills', ['pair', 'filled_at'], unique=False)
    op.create_table('kill_switch_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp_ms', sa.BigInteger(), nullable=False, comment='Unix ms UTC'),
    sa.Column('level', sa.Enum('SOFT', 'HARD', 'EMERGENCY', name='kill_switch_level'), nullable=False),
    sa.Column('previous_state', sa.String(length=20), nullable=False),
    sa.Column('new_state', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('broker_state_mismatch', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kill_switch_events_ts', 'kill_switch_events', ['timestamp_ms'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pair', sa.String(length=6), nullable=False),
    sa.Column('timestamp_ms', sa.BigInteger(), nullable=False, comment='Unix ms UTC'),
    sa.Column('candles', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Timeframe-keyed OHLCV arrays'),
    sa.Column('spread_points', sa.Float(), nullable=False),
    sa.Column('session', sa.Enum('LONDON', 'NY', 'ASIA', 'OVERLAP', name='trading_session'), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_snapshots_pair_ts', 'market_snapshots', ['pair', 'timestamp_ms'], unique=False)
    op.create_table('reconciliation_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp_ms', sa.BigInteger(), nullable=False, comment='Unix ms UTC'),
    sa.Column('redis_positions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Snapshot of Redis open_positions'),
    sa.Column('mt5_positions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Snapshot of MT5 broker positions'),
    sa.Column('mismatch_detected', sa.Boolean(), nullable=False),
    sa.Column('positions_diverged', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Details of divergent positions'),
    sa.Column('action_taken', sa.String(length=20), nullable=True, comment='SOFT|HARD or null if no mismatch'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reconciliation_log_mismatch', 'reconciliation_log', ['mismatch_detected'], unique=False)
    op.create_index('ix_reconciliation_log_ts', 'reconciliation_log', ['timestamp_ms'], unique=False)
    op.create_table('trade_outcomes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pair', sa.String(length=6), nullable=False),
    sa.Column('strategy', sa.Enum('MOMENTUM', 'MEAN_REVERSION', name='strategy_type'), nullable=False),
    sa.Column('regime', sa.Enum('TRENDING_UP', 'TRENDING_DOWN', 'RANGING', 'UNDEFINED', name='regime_type'), nullable=False),
    sa.Column('session', sa.Enum('LONDON', 'NY', 'ASIA', 'OVERLAP', name='trading_session'), nullable=False),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', name='direction_type'), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=False),
    sa.Column('r_multiple', sa.Float(), nullable=False, comment='Actual return / risk'),
    sa.Column('won', sa.Boolean(), nullable=False),
    sa.Column('fill_id', sa.BigInteger(), nullable=True, comment='FK to fills.id if available'),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False, comment='Trade open time'),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False, comment='Trade close time'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trade_outcomes_pair_closed', 'trade_outcomes', ['pair', 'closed_at'], unique=False)
    op.create_index('ix_trade_outcomes_segment', 'trade_outcomes', ['strategy', 'regime', 'session'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trade_outcomes_segment', table_name='trade_outcomes')
    op.drop_index('ix_trade_outcomes_pair_closed', table_name='trade_outcomes')
    op.drop_table('trade_outcomes')
    op.drop_index('ix_reconciliation_log_ts', table_name='reconciliation_log')
    op.drop_index('ix_reconciliation_log_mismatch', table_name='reconciliation_log')
    op.drop_table('reconciliation_log')
    op.drop_index('ix_market_snapshots_pair_ts', table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index('ix_kill_switch_events_ts', table_name='kill_switch_events')
    op.drop_table('kill_switch_events')
    op.drop_index('ix_fills_pair_filled', table_name='fills')
    op.drop_index('ix_fills_order_id', table_name='fills')
    op.drop_table('fills')
    op.drop_index('ix_feature_vectors_pair_ts', table_name='feature_vectors')
    op.drop_table('feature_vectors')
    op.drop_index('ix_candles_pair_tf_ts', table_name='candles')
    op.drop_table('candles')
    # ### end Alembic commands ###
